# Generated by Django 4.1.3 on 2023-06-13 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='./static/pimg')),
                ('status', models.BooleanField(default=False)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='./static/pimg')),
                ('status', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('supplier', models.CharField(max_length=50)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField()),
                ('sp', models.FloatField()),
                ('op', models.FloatField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('proq', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.products')),
            ],
        ),
    ]
